services: 
  todo-app:
      build: .
      container_name: todo-app
      ports:
        - "3000:3000"
      networks:
        - todo-network
      env_file:
        - .env
      depends_on:
        - todo-db
      restart: always 
      

  todo-db:
      image: postgres:14
      container_name: todo-db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1111
        POSTGRES_DB: todo_db
      ports:
        - "5433:5432" 
      networks:
        - todo-network
      volumes:
        - todo_db_data:/var/lib/postgresql/data     

volumes:
  todo_db_data:

networks:
  todo-network:
    driver: bridge        
